question_data = [
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "'Typewriter' is the longest word that can be typed using only the first row on a QWERTY keyboard.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Coca-Cola's original colour was green.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The vapor produced by e-cigarettes is actually water.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The word 'news' originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Cucumbers are usually more than 90% water.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "You are allowed to sell your soul on eBay.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The French word to travel is 'Travail'",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The French word for 'glass' is 'glace'.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Albert Einstein had trouble with mathematics when he was in school.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "'Santa Claus' is a variety of melon.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The scientific name for the Southern Lights is Aurora Australis?",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Haggis is traditionally ate on Burns Night.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}
]
